name: 🛠️ Refactor & Enhancement
description: Propose code restructuring or improvements without adding new features.
title: "[REFACTOR/ENHANCEMENT] "
labels: ["refactor","enhancement"]
assignees: []
body:
  - type: markdown
    attributes:
      value: |
        Use this template to request code cleanup, performance improvements, or architectural tweaks.

  - id: summary
    type: input
    attributes:
      label: **Brief summary**
      placeholder: e.g. `Improve caching strategy in uploads service`
    validations:
      required: true

  - id: motivation
    type: textarea
    attributes:
      label: **Motivation**
      description: Why is this change needed? What problem does it solve?

  - id: current
    type: textarea
    attributes:
      label: **Current behavior**
      description: Describe how the code works today.

  - id: proposed
    type: textarea
    attributes:
      label: **Proposed changes**
      description: What specific refactoring or enhancements do you propose?

  - id: impact
    type: textarea
    attributes:
      label: **Impact**
      description: How will this affect existing functionality or performance?
